#!/usr/bin/env python3
"""
AI Disclosure Module - WordPress AI Guidelines Compliance (Feb 2026)

Per WordPress AI guidelines (https://www.searchenginejournal.com/wordpress-ai-guidelines/566442/):
1. MUST disclose AI involvement clearly at TOP of content
2. MUST verify all data is real (from RAG/Alpaca, not fabricated)
3. MUST avoid "AI slop" (generic, low-value content)
4. MUST have human oversight documented

This module provides standardized disclosure blocks for all blog publishers.
"""
from __future__ import annotations

from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

ET = ZoneInfo("America/New_York")


def get_ai_disclosure_header(content_type: str = "blog") -> str:
    """
    Generate WordPress-compliant AI disclosure header.

    This goes at the TOP of every AI-generated post per WordPress guidelines.
    """
    disclosures = {
        "blog": """
> **AI Disclosure**: This post was generated by our AI trading system (Claude Opus 4.5)
> with human oversight from Igor Ganapolsky. All trade data is pulled from live sources
> (Alpaca API, FRED API) and verified before publication. No data is fabricated.
> Human review completed before posting.
""",
        "rlhf": """
> **AI Disclosure**: This post was auto-generated by our RLHF (Reinforcement Learning
> from Human Feedback) system when the CEO gave feedback. The feedback signal and context
> are real. System metrics are pulled from live data sources. Human oversight: Igor Ganapolsky.
""",
        "ralph": """
> **AI Disclosure**: This post was auto-generated by Ralph, our autonomous AI coding agent.
> The discovery, code changes, and metrics are real - pulled from actual git commits and
> test runs. No humans were directly involved in the fix, but human oversight (Igor Ganapolsky)
> approved this publication workflow.
""",
        "daily": """
> **AI Disclosure**: This daily report was generated by our AI trading system. All financial
> data comes from live sources: Alpaca (broker), FRED (Treasury yields), and our RAG system
> (lessons learned). Every number is verifiable. Human oversight: Igor Ganapolsky.
""",
    }
    return disclosures.get(content_type, disclosures["blog"])


def get_ai_disclosure_footer() -> str:
    """
    Generate WordPress-compliant AI disclosure footer.

    This reinforces disclosure at the bottom per best practices.
    """
    return (
        """
---

## About This Post

**How this post was created:**
- 🤖 **AI Generated**: Content structured by Claude Opus 4.5
- 📊 **Data Sources**: Alpaca API (trades), FRED API (yields), RAG (lessons)
- ✅ **Data Verification**: All numbers pulled from live APIs, no fabrication
- 👤 **Human Oversight**: Igor Ganapolsky reviews publication workflow
- 📅 **Generated**: """
        + datetime.now(ET).strftime("%Y-%m-%d %H:%M ET")
        + """

*Per [WordPress AI Guidelines](https://wordpress.org/ai-guidelines/): We clearly disclose
AI involvement, verify all data, and maintain human oversight.*

**Not financial advice. Paper trading only.**
"""
    )


def verify_data_sources(post_content: str) -> dict:
    """
    Verify that a post doesn't contain fabricated data.

    Checks for common AI hallucination patterns:
    - Generic placeholder numbers ($X,XXX)
    - Suspicious round numbers
    - Missing source citations

    Returns dict with verification status and warnings.
    """
    warnings = []

    # Check for placeholder patterns
    placeholder_patterns = [
        "$X,XXX",
        "$XX,XXX",
        "XX%",
        "[INSERT",
        "TBD",
        "N/A" * 3,  # Too many N/As suggest missing data
    ]

    for pattern in placeholder_patterns:
        if pattern in post_content:
            warnings.append(f"Placeholder detected: {pattern}")

    # Check for suspiciously round numbers in financial context
    import re

    round_numbers = re.findall(r"\$(\d{3,}),000\.00", post_content)
    if len(round_numbers) > 2:
        warnings.append("Multiple suspiciously round dollar amounts detected")

    # Check for data source mentions
    has_alpaca = "alpaca" in post_content.lower()
    has_fred = "fred" in post_content.lower()
    has_rag = "rag" in post_content.lower()

    if not (has_alpaca or has_fred or has_rag):
        warnings.append("No data source citations found (Alpaca, FRED, or RAG)")

    return {
        "verified": len(warnings) == 0,
        "warnings": warnings,
        "data_sources_cited": {
            "alpaca": has_alpaca,
            "fred": has_fred,
            "rag": has_rag,
        },
    }


def add_disclosure_to_post(content: str, content_type: str = "blog") -> str:
    """
    Add AI disclosure to a post, preserving front matter.

    Handles Jekyll/Hugo front matter (---) and adds disclosure after it.
    """
    lines = content.split("\n")

    # Find end of front matter
    front_matter_end = 0
    in_front_matter = False

    for i, line in enumerate(lines):
        if line.strip() == "---":
            if not in_front_matter:
                in_front_matter = True
            else:
                front_matter_end = i + 1
                break

    # Insert disclosure header after front matter
    header = get_ai_disclosure_header(content_type)

    if front_matter_end > 0:
        # Has front matter - insert after
        new_lines = lines[:front_matter_end] + [header] + lines[front_matter_end:]
    else:
        # No front matter - add at beginning
        new_lines = [header] + lines

    # Add footer at end
    footer = get_ai_disclosure_footer()

    return "\n".join(new_lines) + footer


def log_publication(
    post_type: str,
    title: str,
    filepath: str,
    data_verified: bool,
    warnings: list[str] | None = None,
) -> None:
    """
    Log publication to audit trail for WordPress compliance.

    Creates audit record showing human oversight and verification.
    """
    import json

    audit_file = Path(__file__).parent.parent / "data" / "blog_audit_log.json"
    audit_file.parent.mkdir(parents=True, exist_ok=True)

    try:
        if audit_file.exists():
            with open(audit_file) as f:
                records = json.load(f)
        else:
            records = []
    except Exception:
        records = []

    record = {
        "timestamp": datetime.now(ET).isoformat(),
        "post_type": post_type,
        "title": title[:100],
        "filepath": filepath,
        "data_verified": data_verified,
        "warnings": warnings or [],
        "human_oversight": "Igor Ganapolsky",
        "ai_model": "Claude Opus 4.5",
        "compliance": "WordPress AI Guidelines Feb 2026",
    }

    records.append(record)

    # Keep last 500 records
    records = records[-500:]

    with open(audit_file, "w") as f:
        json.dump(records, f, indent=2)


if __name__ == "__main__":
    # Demo the disclosure
    print("=== AI Disclosure Header (blog) ===")
    print(get_ai_disclosure_header("blog"))
    print("\n=== AI Disclosure Header (rlhf) ===")
    print(get_ai_disclosure_header("rlhf"))
    print("\n=== AI Disclosure Footer ===")
    print(get_ai_disclosure_footer())
