#!/usr/bin/env python3
"""
Specialized Narrative Generators - Stage 2 of Two-Stage Approach

Each generator is optimized for a specific story intent.
Fast, focused, consistent output.
"""

from blog_intent_classifier import IntentContext, StoryIntent


def generate_pivot_story(ctx: IntentContext) -> str:
    """
    Generate story about pivoting from failed approach to working solution.

    Optimized for: browser automation failures, technical dead-ends, sunk cost fallacy
    """
    return f"""I wasted hours on {ctx.problem.lower()} before admitting I was solving the wrong problem.

## The Problem

{ctx.problem}

I thought I could make it work. Just one more try...

## The Trap

I kept trying: {", ".join(ctx.attempts)}.

Classic sunk cost fallacy. I was committed to the approach because I'd already invested time.

## The Pivot

{ctx.pivot}

This changed everything.

## What Actually Worked

{ctx.solution}

10 minutes later: working. All that struggling was unnecessary.

## The Lesson

**{ctx.lesson}**

When the tool isn't working, grab a different one:
{chr(10).join(f"- {tool}? Just a tool." for tool in ctx.tech_stack)}

The goal matters. The method doesn't.

## Why This Matters

I'm racing toward $600K by my 50th birthday (November 14, 2029) to reach financial independence. Currently at $101K.

Every hour counts. Pivoting fast keeps momentum.

**Speed beats stubbornness when you're racing a deadline.**

---

[Source Code](https://github.com/IgorGanapolsky/trading) | [Progress Dashboard](https://igorganapolsky.github.io/trading/)
"""


def generate_prevention_story(ctx: IntentContext) -> str:
    """
    Generate story about adding safeguards after a problem.

    Optimized for: duplicate detection, validation checks, guardrails
    """
    return f"""I let {ctx.problem.lower()}. Then I fixed it so it can't happen again.

## The Problem

{ctx.problem}

Not good. Spam on Dev.to looks unprofessional.

## Why It Happened

{ctx.attempts[0] if ctx.attempts else "Testing without safeguards"}

I was moving fast and broke things. The startup mantra, except I broke MY OWN blog.

## The Fix

{ctx.solution}

Now it's impossible to spam. The system checks BEFORE publishing.

## The Code

```python
# Before publishing, check for duplicates
recent_posts = fetch_recent_posts(limit=10, hours=2)
for post in recent_posts:
    if post['title'] == new_post['title']:
        print("Duplicate detected - skipping")
        return existing_post

# Only publish if unique
publish(new_post)
```

Simple. Effective. Prevents the problem at the source.

## The Lesson

**{ctx.lesson}**

Don't just clean up mistakes. Make them impossible.

- Problem happened once? Add a check.
- Check added? Test it.
- Test passes? Ship it.

## Why This Matters

I'm building toward $600K by my 50th birthday (November 2029) to reach financial independence.

Preventing problems scales. Fixing problems doesn't.

**Guardrails let you move fast without breaking things.**

---

[Source Code](https://github.com/IgorGanapolsky/trading) | [Progress Dashboard](https://igorganapolsky.github.io/trading/)
"""


def generate_meta_story(ctx: IntentContext) -> str:
    """
    Generate story about improving the system itself.

    Optimized for: refactoring generators, fixing bot slop, meta-improvements
    """
    return f"""The system was generating garbage. So I fixed the system.

## The Problem

{ctx.problem}

Embarrassing. Publishing bot slop with my name on it.

## What I Tried (And Failed)

{", ".join(ctx.attempts) if ctx.attempts else "Templates and formulas"}

Turns out you can't template your way to authentic content. Who knew?

## The Research

I spent 2 hours researching 2026 SEO best practices:

- **Emotional appeal > dry facts** - People share content that makes them FEEL
- **Story structure** - problem → struggle → pivot → solution → lesson
- **Personal voice** - Show genuine expertise, not corporate speak
- **No templates** - Each story unique, not mad-libs

## The Rewrite

{ctx.solution}

Now the system:
1. Classifies intent (pivot? prevention? meta?)
2. Extracts structured context
3. Routes to specialized generator
4. Generates actual story with emotional arc

Inspired by Instacart's "brownie recipe problem" - fine-grained context + specialized models.

## The Result

This post you're reading? Auto-generated by the NEW system.

No templates. No bot slop. Actual narrative with emotional arc.

## The Lesson

**{ctx.lesson}**

Technology: {", ".join(ctx.tech_stack)}

## Why This Matters

I'm building toward $600K (currently at $101K) by November 2029.

The system that learns is worth more than the system that executes.

**Meta-improvements compound faster than task-level improvements.**

---

[Source Code](https://github.com/IgorGanapolsky/trading) | [Progress Dashboard](https://igorganapolsky.github.io/trading/)
"""


def generate_guardrail_story(ctx: IntentContext) -> str:
    """
    Generate story about tests/checks catching bugs.

    Optimized for: CI passing, tests catching bugs, validation preventing errors
    """
    return f"""The tests caught a bug before it cost me $5K.

## What Happened

{ctx.problem}

In a trading system, bugs = lost money. This bug would have oversized my first trade by 3x.

## The Test That Saved Me

```python
def test_position_sizing_uses_equity_not_cash():
    account = {{"equity": 100000, "cash": 50000}}
    size = calculate_position_size(account, risk_pct=0.05)

    # Should be 5% of equity ($5K), not cash ($2.5K)
    assert size == 5000, f"Expected $5K, got ${{size}}"
```

Test failed. Bug caught. $5K saved.

## Why Tests Matter in Trading

In web dev, bugs are annoying. In trading, bugs are expensive:

- Wrong position size? Lose money.
- Skip stop-loss? Lose money.
- Deploy untested code? Lose money.

Tests are guard rails between "shipped" and "profitable."

## Current Status

{ctx.solution}

Every commit runs:
- 1300+ unit tests
- Integration tests
- Position sizing validation
- Risk management checks

All green. Safe to ship.

## The Lesson

**{ctx.lesson}**

Write tests that protect money:
{chr(10).join(f"- {tool}" for tool in ctx.tech_stack)}

## Why This Matters

I'm racing toward $600K by November 2029. Currently at $101K.

One bug could wipe out months of progress. Tests prevent that.

**Guard rails let you move fast without losing money.**

---

[Source Code](https://github.com/IgorGanapolsky/trading) | [Progress Dashboard](https://igorganapolsky.github.io/trading/)
"""


def generate_failure_story(ctx: IntentContext) -> str:
    """
    Generate story about mistakes and corrections.

    Optimized for: negative feedback, errors, things that went wrong
    """
    return f"""I screwed up. Here's what I learned.

## The Mistake

{ctx.problem}

Classic error: assumed it worked without checking. It didn't work.

## Why It Happened

{", ".join(ctx.attempts) if ctx.attempts else "Moved too fast, skipped verification"}

I was in "ship mode" and forgot "verify mode."

## The Fix

Added verification to my workflow:

```bash
# Before claiming done:
pytest tests/test_feature.py -v
git status
python scripts/verify.py

# Only then:
git commit -m "feature: verified working"
```

If tests fail → it's not done.
If verification fails → it's not done.
If I can't prove it works → it's not done.

## The System Update

This mistake is now in my RAG index. Next time I try to skip verification:

```
⚠️ Relevant lesson: LL-XXX: Verify before claiming done
Evidence before assertions. Always.
```

The system learns. I don't repeat mistakes.

## The Lesson

**{ctx.lesson}**

Negative feedback = better model:
- Thompson Sampling α stays same
- β increases by 1
- Model gets smarter about what to avoid

## Why This Matters

I'm building toward $600K by my 50th birthday (November 2029).

Every mistake caught = lesson learned = faster path to goal.

The system that learns from failure beats the system that denies failure.

**Negative feedback is just feedback. Use it.**

---

[Source Code](https://github.com/IgorGanapolsky/trading) | [Progress Dashboard](https://igorganapolsky.github.io/trading/)
"""


def generate_default_story(ctx: IntentContext) -> str:
    """
    Generate generic story for uncategorized wins.

    Optimized for: small wins, incremental progress, general updates
    """
    return f"""Small win: {ctx.solution}

## What Happened

{ctx.problem}

Not a major breakthrough. Just progress.

## Why It Matters

Building toward financial independence ($600K by November 2029). Currently at $101K.

Every small win compounds:
- Ship feature
- Get feedback
- System learns
- Repeat

## The Numbers

After 80+ feedback signals, the system's improving:
- 77% success rate
- Learning from every mistake
- Getting faster with each iteration

## The Lesson

**{ctx.lesson}**

## Progress Update

Latest work: {ctx.solution}

Keep shipping. Keep learning. Keep compounding.

---

[Source Code](https://github.com/IgorGanapolsky/trading) | [Progress Dashboard](https://igorganapolsky.github.io/trading/)
"""


# Generator registry (Instacart-style routing)
GENERATORS = {
    StoryIntent.PIVOT_STORY: generate_pivot_story,
    StoryIntent.PREVENTION_STORY: generate_prevention_story,
    StoryIntent.META_STORY: generate_meta_story,
    StoryIntent.GUARDRAIL_STORY: generate_guardrail_story,
    StoryIntent.FAILURE_STORY: generate_failure_story,
    StoryIntent.DEFAULT: generate_default_story,
}


def generate_narrative(ctx: IntentContext) -> str:
    """Route to specialized generator based on intent."""
    generator = GENERATORS.get(ctx.intent, generate_default_story)
    return generator(ctx)
