#!/usr/bin/env python3
"""Generate Ralph Weekly Digest markdown file."""

import subprocess
from datetime import datetime, timedelta
from pathlib import Path


def run_cmd(cmd: str) -> str:
    """Run shell command and return output."""
    try:
        result = subprocess.run(cmd, shell=True, capture_output=True, text=True, timeout=30)
        return result.stdout.strip()
    except Exception:
        return ""


def main():
    today = datetime.now().strftime("%Y-%m-%d")
    week_start = (datetime.now() - timedelta(days=datetime.now().weekday() + 1)).strftime(
        "%Y-%m-%d"
    )

    digest_file = Path(f"docs/_posts/{today}-ralph-weekly-digest.md")
    digest_file.parent.mkdir(parents=True, exist_ok=True)

    ralph_commits = len(
        run_cmd(
            "git log --since='7 days ago' --oneline --grep='ralph\\|self-heal\\|auto-fix'"
        ).split("\n")
    )
    fix_commits = len(run_cmd("git log --since='7 days ago' --oneline --grep='fix'").split("\n"))
    feat_commits = len(run_cmd("git log --since='7 days ago' --oneline --grep='feat'").split("\n"))
    total_commits = len(run_cmd("git log --since='7 days ago' --oneline").split("\n"))
    test_count = run_cmd("grep -r 'def test_' tests/ 2>/dev/null | wc -l")
    py_files = run_cmd("find src/ scripts/ -name '*.py' 2>/dev/null | wc -l")

    fixes_log = (
        run_cmd("git log --since='7 days ago' --oneline --grep='fix\\|heal\\|auto' | head -15")
        or "None this week"
    )
    feats_log = (
        run_cmd("git log --since='7 days ago' --oneline --grep='feat' | head -10")
        or "None this week"
    )

    content = f"""---
layout: post
title: "Ralph Weekly Digest: Week of {week_start}"
date: {today}
categories: [ralph, weekly-digest, ai-trading]
tags: [ai, trading, automation, self-healing, claude]
---

# Ralph Weekly Digest

**Week of {week_start} to {today}**

This week, Ralph - our AI CTO - has been working around the clock to improve the AI Trading System. Here's what happened.

---

## Activity Summary

| Metric | Count |
|--------|-------|
| Total commits | {total_commits} |
| Ralph/self-heal commits | {ralph_commits} |
| Bug fixes | {fix_commits} |
| New features | {feat_commits} |
| Tests in codebase | {test_count} |
| Python files | {py_files} |

## Fixes Applied This Week

```
{fixes_log}
```

## New Features

```
{feats_log}
```

## Code Quality Improvements

- Automated linting with ruff
- Self-healing CI that fixes issues automatically
- Proactive security scanning with bandit
- Dead code detection with vulture

## What's Next

Ralph will continue:
- Monitoring CI health 24/7
- Auto-fixing lint and format issues
- Running proactive security scans
- Publishing discoveries to the blog

---

*This digest was auto-generated by Ralph Mode. The AI CTO never sleeps.*

**Links:**
- [GitHub Repository](https://github.com/IgorGanapolsky/trading)
- [AI Trading Blog](https://igorganapolsky.github.io/trading/)
"""

    digest_file.write_text(content)
    print(f"Generated: {digest_file}")
    print(f"has_activity={'true' if total_commits > 0 else 'false'}")


if __name__ == "__main__":
    main()
