#!/usr/bin/env python3
"""
RLHF Blog Publisher - Musashi Style

Short. Direct. Visual. Like The Book of Five Rings.
Every thumbs up/down creates a concise lesson with a diagram.

Publishes to: GitHub Pages, Dev.to, LinkedIn
"""

import json
import os
import re
import sys
import time
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

import requests

ET = ZoneInfo("America/New_York")
REPO_URL = "https://github.com/IgorGanapolsky/trading"


def get_rlhf_stats() -> dict:
    """Get RLHF feedback statistics."""
    stats_file = Path("data/feedback/stats.json")
    if stats_file.exists():
        with open(stats_file) as f:
            return json.load(f)
    return {"positive": 0, "negative": 0, "total": 0}


def get_model_stats() -> dict:
    """Get Thompson Sampling model stats."""
    model_file = Path("../models/ml/feedback_model.json")
    if model_file.exists():
        with open(model_file) as f:
            return json.load(f)
    return {"alpha": 1, "beta": 1}


def get_equity() -> float:
    """Get current account equity."""
    state_file = Path("data/system_state.json")
    if state_file.exists():
        with open(state_file) as f:
            state = json.load(f)
            paper = state.get("paper_account", {})
            return paper.get("equity", paper.get("current_equity", 100000))
    return 100000


def generate_title(signal: str, context: str) -> str:
    """Generate short, punchy title."""
    ctx = context.lower()

    if signal == "positive":
        if "test" in ctx:
            return "Tests Pass. Ship It."
        elif "rlhf" in ctx:
            return "The Machine Learns"
        elif "iron condor" in ctx or "trade" in ctx:
            return "Trade Approved. Capital Protected."
        elif "blog" in ctx:
            return "Words Into Action"
        else:
            return "Small Win. Keep Moving."
    else:
        if "wrong" in ctx or "incorrect" in ctx:
            return "Wrong. Corrected."
        elif "slow" in ctx or "time" in ctx:
            return "Too Slow. Faster Next Time."
        elif "money" in ctx or "loss" in ctx:
            return "Rule #1 Violated"
        else:
            return "Mistake Made. Lesson Learned."


def generate_mermaid_diagram(signal: str, stats: dict, model: dict) -> str:
    """Generate a Mermaid diagram showing the RLHF flow."""
    total = stats.get("total", 0)
    positive = stats.get("positive", 0)
    negative = stats.get("negative", 0)
    alpha = model.get("alpha", 1)
    beta = model.get("beta", 1)
    win_rate = (alpha / (alpha + beta)) * 100 if (alpha + beta) > 0 else 50

    if signal == "positive":
        return f"""```mermaid
flowchart LR
    A[👍 Feedback] --> B[Thompson α+1]
    B --> C[Model Updated]
    C --> D[Better Decisions]

    style A fill:#22c55e,color:#fff
    style D fill:#22c55e,color:#fff
```

**Stats**: {positive}👍 / {negative}👎 = {win_rate:.0f}% success rate"""
    else:
        return f"""```mermaid
flowchart LR
    A[👎 Feedback] --> B[Thompson β+1]
    B --> C[Lesson Indexed]
    C --> D[RAG Reminder]
    D --> E[Won't Repeat]

    style A fill:#ef4444,color:#fff
    style E fill:#22c55e,color:#fff
```

**Stats**: {positive}👍 / {negative}👎 | This mistake now prevents future ones."""


def generate_post(signal: str, intensity: float, context: str) -> dict:
    """Generate a short, direct blog post with diagram."""
    now = datetime.now(ET)
    date_str = now.strftime("%Y-%m-%d")
    timestamp = now.strftime("%Y-%m-%d %H:%M:%S")

    title = generate_title(signal, context)
    stats = get_rlhf_stats()
    model = get_model_stats()
    equity = get_equity()
    diagram = generate_mermaid_diagram(signal, stats, model)

    # The lesson - one sentence
    if signal == "positive":
        lesson = "What worked gets reinforced. The system improves."
    else:
        lesson = "What failed gets remembered. The system adapts."

    # Keep it SHORT - Musashi style
    content = f"""---
layout: post
title: "{title}"
date: {timestamp}
categories: [rlhf, trading]
tags: [{signal}, rlhf, ai-trading]
---

> {context[:150]}

{"👍" if signal == "positive" else "👎"} **Signal**: {signal} (intensity: {intensity})

## The Flow

{diagram}

## The Lesson

{lesson}

## Current State

| Metric | Value |
|--------|-------|
| Account | ${equity:,.0f} |
| RLHF Signals | {stats.get("total", 0)} |
| Win Rate | {(model.get("alpha", 1) / (model.get("alpha", 1) + model.get("beta", 1)) * 100):.0f}% |

---

*Auto-generated by RLHF system. [Source]({REPO_URL})*
"""

    return {
        "title": title,
        "content": content,
        "date": date_str,
        "tags": [signal, "rlhf", "aitrading", "buildinginpublic"],
        "signal": signal,
        "summary": f"{title} - {lesson}",  # For LinkedIn
    }


def save_to_github_pages(post: dict) -> str | None:
    """Save post to GitHub Pages."""
    posts_dir = Path("docs/_posts")
    posts_dir.mkdir(parents=True, exist_ok=True)

    slug = "win" if post["signal"] == "positive" else "lesson"
    filename = f"{post['date']}-rlhf-{slug}.md"
    filepath = posts_dir / filename

    if filepath.exists():
        ts = datetime.now(ET).strftime("%H%M")
        filename = f"{post['date']}-rlhf-{slug}-{ts}.md"
        filepath = posts_dir / filename

    filepath.write_text(post["content"])
    print(f"✅ GitHub Pages: {filepath}")
    return str(filepath)


def publish_to_devto(post: dict) -> dict | None:
    """Publish to Dev.to."""
    api_key = os.environ.get("DEVTO_API_KEY") or os.environ.get("DEV_TO_API_KEY")
    if not api_key:
        print("⚠️ DEVTO_API_KEY / DEV_TO_API_KEY not set")
        return None

    # Remove Jekyll front matter
    content = re.sub(r"---\n.*?---\n", "", post["content"], flags=re.DOTALL)

    payload = {
        "article": {
            "title": post["title"],
            "body_markdown": content,
            "published": True,
            "tags": post["tags"][:4],
            "series": "AI Trading RLHF",
        }
    }

    try:
        resp = requests.post(
            "https://dev.to/api/articles",
            headers={"api-key": api_key, "Content-Type": "application/json"},
            json=payload,
            timeout=30,
        )
        if resp.status_code == 201:
            result = resp.json()
            print(f"✅ Dev.to: {result.get('url')}")
            return result
        else:
            print(f"⚠️ Dev.to failed: {resp.status_code} - {resp.text[:100]}")
            return None
    except Exception as e:
        print(f"⚠️ Dev.to error: {e}")
        return None


def queue_for_linkedin(post: dict, devto_url: str = None) -> bool:
    """Queue post for LinkedIn via /linkedin-post skill (browser automation)."""
    # Use existing LinkedIn queue system
    queue_file = Path(__file__).parent.parent.parent / "docs" / "linkedin_post_queue.json"

    if not queue_file.exists():
        print("⚠️ LinkedIn queue not found - LinkedIn posting disabled")
        return False

    # Short LinkedIn post with link
    link = devto_url or "https://igorganapolsky.github.io/trading/"
    emoji = "✅" if post["signal"] == "positive" else "📚"

    content = f"""{emoji} {post["title"]}

{post["summary"]}

Building an AI trading system that learns from every decision.

#AITrading #RLHF #BuildingInPublic #FinTech

{link}"""

    # Add to queue
    try:
        with open(queue_file) as f:
            data = json.load(f)

        # Get next ID
        next_id = max([item.get("id", 0) for item in data.get("queue", [])], default=0) + 1

        # Add new entry
        data["queue"].append(
            {
                "id": next_id,
                "title": post["title"],
                "status": "pending",
                "content": content,
                "source": "rlhf_auto",
                "signal": post["signal"],
                "created_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                "tags": ["AITrading", "RLHF", "BuildingInPublic", "FinTech"],
            }
        )

        with open(queue_file, "w") as f:
            json.dump(data, f, indent=2)

        print(f"✅ LinkedIn: Queued (ID: {next_id}, use /linkedin-post)")
        return True
    except Exception as e:
        print(f"⚠️ LinkedIn queue error: {e}")
        return False


def main():
    """Main entry point."""
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("--signal", required=True, choices=["positive", "negative"])
    parser.add_argument("--intensity", type=float, default=0.5)
    parser.add_argument("--context", required=True)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    print(f"📝 RLHF Blog: {args.signal} ({args.intensity})")

    post = generate_post(args.signal, args.intensity, args.context)
    print(f"   Title: {post['title']}")

    if args.dry_run:
        print("\n--- DRY RUN ---")
        print(post["content"])
        return 0

    # Publish to all platforms
    gh_path = save_to_github_pages(post)
    devto_result = publish_to_devto(post)
    devto_url = devto_result.get("url") if devto_result else None
    linkedin_ok = queue_for_linkedin(post, devto_url)

    print(f"\n✅ Published to {sum([bool(gh_path), bool(devto_result), linkedin_ok])}/3 platforms")
    return 0


if __name__ == "__main__":
    sys.exit(main())
